title: "Proyecto Arcadia - 15 Años de RPG Superheroico"
description: "Archivo histórico completo de tres campañas épicas de superhéroes: La Familia, Génesis y La Fuerza Oculta"
baseurl: "/arcadia"
url: "https://LudoBermejoES.github.io"

# GitHub Pages configuration
remote_theme: Jagjeet/comicbook-theme
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-remote-theme

# Navigation
header_pages:
  - campaigns/la-familia/index.md
  - campaigns/genesis/index.md  
  - campaigns/la-fuerza-oculta/index.md

# Site settings
author: "Mesa de Arcadia"
email: "ludo.bermejo@example.com"

# Social media
github_username: LudoBermejoES

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Collections for better organization
collections:
  campaigns:
    output: true
    permalink: /:collection/:name/
  sessions:
    output: true
    permalink: /:collection/:name/
  comics:
    output: true
    permalink: /:collection/:name/

# SEO settings
lang: es
locale: es_ES

# Google Analytics (optional)
# google_analytics: UA-XXXXXXXX-X

# Pagination
paginate: 10
paginate_path: "/page:num/"

# Timezone
timezone: Europe/Madrid